name: flutter_app_icon_change
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  image_path: "assets/images/new_icon.png"
  adaptive_icon_background: "#235586"
  adaptive_icon_foreground: "assets/images/new_icon.png"
  ios: true
  remove_alpha_ios: true
  android: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
